name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Cache
      uses: actions/cache@v3.0.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: 
          dist/
        # An explicit key for restoring and saving the cache
        key: 
          dist
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        #restore-keys: # optional
        # The chunk size used to split up large files during upload, in bytes
        #upload-chunk-size: # optional
